### ISSUE TITLE
in metadata.csv, the SourceUrl for all samples is the same

### ISSUE THREAD

**Issue by psolaimani** [Bioconductor/TENxBrainData#4]
Hi Aaron,
I wanted to download the different files you have generated from the 10X study, to start experimenting. I see that in `TENxBrainData/inst/extdata/metadata.csv` the `SourceUrl` for all the samples is the same. Could you please provide the correct urls.

Thanks a lot!

**Comment by mtmorgan** [comment]
The single source url is processed to four different files. The files are available in ExperimentHub

```
library(ExperimentHub)
hub = ExperimentHub()
query(hub, "TENxBrainData")
hub[["EH1040"]]
```

See also https://github.com/Bioconductor/TENxBrainData/blob/master/R/TENxBrainData.R
